### PR TITLE
AVX19859: update marketplace stack

### PR DESCRIPTION
**Pull request by shuoliugit**

### CODE REVIEW

**Review by brian-avery — APPROVED** [review]

**Comment by brian-avery** [comment]
If I try deploying this via the OCI import stack, I get the following. Availability domain is a drop down.

image

```
Error: Incorrect attribute value type

  on main.tf line 54, in data "oci_identity_availability_domain" "ad" 

  54:   ad_number      = var.availability_domain

    |----------------

    | var.availability_domain is "Qmuz:US-ASHBURN-AD-1"

Inappropriate value for attribute "ad_number"  a number is required.
```

**Comment by shuoliugit** [comment]
> If I try deploying this via the OCI import stack, I get the following. Availability domain is a drop down.
> 
> image
> 
> ```
> Error: Incorrect attribute value type
> 
>   on main.tf line 54, in data "oci_identity_availability_domain" "ad" 
> 
>   54:   ad_number      = var.availability_domain
> 
>     |----------------
> 
>     | var.availability_domain is "Qmuz:US-ASHBURN-AD-1"
> 
> Inappropriate value for attribute "ad_number"  a number is required.
> ```

I removed the data source, please try again.

**Comment by brian-avery** [comment]
Thanks. Tested both Pay as You Go and BYOL with this. BYOL worked out of the box. PAYG needs a couple of tiny modifications (6.3.0 replaced with 6.3). Should we include it in this PR or open a different one?

**Comment by brian-avery** [comment]
Formatting doesn't copy to GitHub as well as I'd like

image

**Review by brian-avery — APPROVED** [review]

**Review by zhiqiangjin — APPROVED** [review]

**Pull request merged**
